# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

import torch
from torch_geometric.datasets import QM9

from botorch.fit import fit_gpytorch_mll
from botorch.models import SingleTaskGP
from botorch.test_functions.synthetic import Rosenbrock, Michalewicz
from gpytorch.mlls import ExactMarginalLogLikelihood

In [3]:
import matplotlib.pyplot as plt

# Gradient-based Optimization

## Objective

In [84]:
from src.flory import FloryHuggins

In [98]:
n_components = 3
objective = FloryHuggins(n_components, noise=0.0)
objective.set_pairwise(0, 1, 5.0)
objective.set_pairwise(1, 2, -5.0)
objective.set_pairwise(0, 2, 2.5)

objective.pairwise

tensor([[ 0.0000,  5.0000,  2.5000],
        [ 5.0000,  0.0000, -5.0000],
        [ 2.5000, -5.0000,  0.0000]])

In [101]:
x = torch.tensor([0.5, 0.4, 0.1])

objective(x)

tensor(-0.0183)

# Molecular Design


## Dataset

In [18]:
dataset = QM9(root="data")

In [12]:
dataset[0].num_node_features

11

In [53]:
dataset[-3].z

tensor([6, 7, 6, 6, 6, 6, 6, 6, 7, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
dataset[0].edge_index

tensor([[0, 0, 0, 0, 1, 2, 3, 4],
        [1, 2, 3, 4, 0, 0, 0, 0]])